name: GitHub Actions Demo
run-name: ${{ github.actor }} is GitHub Actions 🚀
on: [push]
jobs:
  Learning-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Event ${{ github.event_name }}"
      - run: echo "My Name is Alex"
